services:
  postgres-account:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./sql/create_account.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-ride:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    volumes:
      - ./sql/create_ride.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-payment:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5434:5432"
    volumes:
      - ./sql/create_payment.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672